config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a35ed77fa2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <%= form_for(@task) do |f| %>
    <div class="form-group">
    <%= f.label :title, class: 'mt-3' %>
    <%= f.text_field :title, class: 'form-control d-block mt-1 mb-1 w-100' %>
  </div>

  <div class="form-group">
    <%= f.label :details, class: 'mt-3' %>
    <%= f.text_field :details, class: 'form-control d-block mt-1 mb-1 w-100'  %>
  </div>

   <div class="form-group form-check">
    <%= f.check_box(:completed, class: 'form-check-input') %>
    <%= label_tag(:completed, "Mark as completed", class: 'form-check-label') %>
  </div>
  <%= f.submit class: 'btn btn-primary d-block mt-3 mb-3' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container-fluid bg-light">
  <div class="row vh-100">
    <div class="col-md-6 mx-auto my-auto p-3 bg-white border border-white rounded-lg shadow">
      <h2>Edit task</h2>
        <%= render 'form', task: @task %>
      <hr>
      <%= link_to tasks_path do %>
        <div class="d-flex align-items-center ">
          <i class="fas fa-undo-alt pr-2 text-primary"></i>
          <span>Go back</span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container-fluid bg-light">
  <div class="row vh-100">
    <div class="col-md-6 mx-auto my-auto p-3 bg-white border border-white rounded-lg shadow">
      <h1 class="mb-3">My tasks:</h1>
        <% @tasks.each do |task| %>
      <div class="d-flex">
        <p><% if task.completed == true %>
              <input type="checkbox" disabled="disabled" checked>
            <% else %>
              <input type="checkbox" disabled="disabled">
            <% end %>
        </p>
        <p class="pl-3"> <%= link_to task.title, task_path(task) %></p>
          <p><%= link_to task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
            <i class="far fa-trash-alt pl-3"></i>
              <% end %>
          </p>
      </div>
        <% end %>
        <hr>
      <%= link_to new_task_path do %>
        <div class="d-flex align-items-center ">
          <i class="fas fa-plus pr-2 text-primary"></i>
          <span>Create new task</span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container-fluid bg-light">
  <div class="row vh-100">
    <div class="col-md-6 mx-auto my-auto p-3 bg-white border border-white rounded-lg shadow">
      <h2>New task</h2>
        <%= render 'form', task: @task %>
        <hr>
      <%= link_to tasks_path do %>
        <div class="d-flex align-items-center ">
          <i class="fas fa-undo-alt pr-2 text-primary"></i>
          <span>Go back</span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container-fluid bg-light">
  <div class="row vh-100">
    <div class="col-md-6 mx-auto my-auto p-3 bg-white border border-white rounded-lg shadow">
      <h3 class="font-weight-normal">Your task:</h3>
      <h2 class="text-primary"><%= @task.title %></h2>
      <p><u>What:</u> <%= @task.details %></p>
      <p><% if @task.completed == true %>
            <input type="checkbox" disabled="disabled" checked>
            <label class="text-success">This task has been completed</label>
            <% else %>
            <input type="checkbox" disabled="disabled">
            <label class="text-danger">This task hasn't been completed yet</label>
            <% end %>
      </p>
        <%= link_to 'Edit your task', edit_task_path, class: 'btn btn-primary' %>

      <hr>
      <%= link_to tasks_path do %>
        <div class="d-flex align-items-center ">
          <i class="fas fa-undo-alt pr-2 text-primary"></i>
          <span>Go back</span>
        </div>
      <% end %>
    </div>
  </div>
</div>